# Generated by Django 5.0.2 on 2024-03-30 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=100)),
                ('Details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='foodchart_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('daytime', models.CharField(max_length=100)),
                ('daytype', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='order_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('image', models.FileField(upload_to='')),
                ('stock', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='inventory_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('stock', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Charity_Scheme.department_table')),
            ],
        ),
        migrations.AddField(
            model_name='department_table',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Charity_Scheme.login_table'),
        ),
        migrations.CreateModel(
            name='need_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=300)),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Charity_Scheme.department_table')),
            ],
        ),
        migrations.CreateModel(
            name='orderdetail_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Charity_Scheme.order_table')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Charity_Scheme.product_table')),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Charity_Scheme.login_table')),
            ],
        ),
        migrations.AddField(
            model_name='order_table',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Charity_Scheme.user_table'),
        ),
        migrations.CreateModel(
            name='needresponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('needid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Charity_Scheme.need_table')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Charity_Scheme.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='inventoryrequest_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('stock', models.IntegerField()),
                ('reason', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Charity_Scheme.inventory_table')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Charity_Scheme.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='fooddonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('foodchart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Charity_Scheme.foodchart_table')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Charity_Scheme.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='volunteers_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
                ('aadharno', models.BigIntegerField()),
                ('status', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Charity_Scheme.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='patientinfo_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('phone', models.BigIntegerField()),
                ('disease', models.CharField(max_length=100)),
                ('Image', models.FileField(upload_to='')),
                ('idproof', models.FileField(upload_to='')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Charity_Scheme.volunteers_table')),
            ],
        ),
    ]
