# Generated by Django 5.0.2 on 2024-04-06 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Charity_Scheme', '0005_patient_enable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='patient_enable',
        ),
    ]
